### ISSUE TITLE
Status request

### ISSUE THREAD

**Issue by mariusl** [regeg/ArdunioTHC#2]
Hi
Not really an issue but rather asking what the status of the project is currently.
Do you use the project with your plasma and how is it performing?
I am looking at using it with a DC motor on the Z axis so I will have to make some changes to the code  and hardware to drive the motor but I will only start making changes if you feel it is stable as it is at this moment.

**Comment by regeg** [comment]
I've had minimal feedback on the software.  I know that one or two people have it up and running.

But.... this was designed assuming that Mach would be doing the Z-height control.  I don't know if you'd have good enough latency to do the control with the Arduino.  I'd also recommend a touch and go head so that any problems during use don't do a hard physical crash of the plasma tip.  Again, the touch and go switch needs a very low latency response too.

**Comment by mariusl** [comment]
I was wondering about the latency. It just means I have to replace the DC motor with a stepper on Z and let Mach do the work.
Thanks for the feedback.
